import type { Metadata } from "next";
import "./globals.css";
import { dmSans, openSans } from "@/app/fonts";

import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Online Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${dmSans.variable} antialiased bg-gray-100`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
